### ISSUE TITLE
Runing testcli.js is not working

### ISSUE THREAD

**Issue by alexiicon** [bloq/cpptrade#6]
$ ./testcli.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/alex/cpptrade/testcli.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
alex@ubuntu:~/cpptrade$ 

Hi, it looks like something is missing from project :)

**Comment by jgarzik** [comment]
You need to run `npm install` to install JavaScript dependencies
